import Foundation

/// A how-to article the assistant answers from. Steps use the app's exact button and menu names.
struct HelpArticle: Identifiable, Hashable {
    let id: String
    let title: String
    let area: String
    let keywords: [String]
    let summary: String
    let steps: [String]
    var tips: [String] = []
    /// Where "Take me there" goes: today, pipeline, measure, jobs, schedule, customers, invoices, learn,
    /// settings:<section>, or job:<tab> (needs a job).
    var screen: String?
    /// Places on screen this article is about (HelpSpot ids), for "show me".
    var spots: [String] = []
}

/// A place on screen the assistant can point at with a pulsing ring.
struct HelpSpot: Hashable {
    enum Place: Hashable {
        case always              // the sidebar, visible on every screen
        case screen(String)      // today, pipeline, measure, jobs, schedule, customers, invoices, learn
        case jobTab(String)      // a tab of an open job: overview, measure, estimate, schedule, logs, photos, invoice
        case settings(String)    // a Settings section
        case assistant           // the assistant panel (open while the assistant is answering)
    }
    let id: String
    let label: String
    let place: Place
}

enum KnowledgeBase {
    // MARK: Spots

    static let spots: [HelpSpot] = [
        HelpSpot(id: "sidebar.search", label: "the Search box at the top of the sidebar (⌘K)", place: .always),
        HelpSpot(id: "sidebar.today", label: "Today in the sidebar", place: .always),
        HelpSpot(id: "sidebar.pipeline", label: "Pipeline in the sidebar", place: .always),
        HelpSpot(id: "sidebar.measure", label: "Measure in the sidebar", place: .always),
        HelpSpot(id: "sidebar.jobs", label: "Jobs in the sidebar", place: .always),
        HelpSpot(id: "sidebar.schedule", label: "Schedule in the sidebar", place: .always),
        HelpSpot(id: "sidebar.customers", label: "Customers in the sidebar", place: .always),
        HelpSpot(id: "sidebar.invoices", label: "Invoices in the sidebar", place: .always),
        HelpSpot(id: "sidebar.crews", label: "Crews in the sidebar", place: .always),
        HelpSpot(id: "sidebar.recent", label: "Recent jobs in the sidebar", place: .always),
        HelpSpot(id: "sidebar.assistant", label: "Assistant in the sidebar (⌘J)", place: .always),
        HelpSpot(id: "sidebar.learn", label: "Learn Stringline in the sidebar", place: .always),
        HelpSpot(id: "sidebar.settings", label: "Settings & rates in the sidebar", place: .always),
        HelpSpot(id: "sidebar.data", label: "the PavingData folder card at the bottom of the sidebar", place: .always),
        HelpSpot(id: "today.weather", label: "the Paving weather card", place: .screen("today")),
        HelpSpot(id: "today.attention", label: "the Needs attention card", place: .screen("today")),
        HelpSpot(id: "pipeline.board", label: "the pipeline board", place: .screen("pipeline")),
        HelpSpot(id: "pipeline.newLead", label: "the New lead button", place: .screen("pipeline")),
        HelpSpot(id: "pipeline.showLost", label: "the Show lost button", place: .screen("pipeline")),
        HelpSpot(id: "measure.search", label: "the Where's the lot? search box", place: .screen("measure")),
        HelpSpot(id: "job.tabs", label: "the job's tabs", place: .jobTab("overview")),
        HelpSpot(id: "job.menu", label: "the ⋯ button at the top right of the job", place: .jobTab("overview")),
        HelpSpot(id: "jobMeasure.tools", label: "the drawing tools on the map", place: .jobTab("measure")),
        HelpSpot(id: "jobMeasure.imagery", label: "the Apple / Esri imagery switch", place: .jobTab("measure")),
        HelpSpot(id: "jobMeasure.lookAround", label: "the Look Around button", place: .jobTab("measure")),
        HelpSpot(id: "jobMeasure.send", label: "the Send to estimate button", place: .jobTab("measure")),
        HelpSpot(id: "jobEstimate.options", label: "the option buttons (Option A, B…) and Add option", place: .jobTab("estimate")),
        HelpSpot(id: "jobEstimate.lines", label: "the line items table and Add line item", place: .jobTab("estimate")),
        HelpSpot(id: "jobEstimate.summary", label: "the Bid summary with the Profit slider", place: .jobTab("estimate")),
        HelpSpot(id: "jobEstimate.send", label: "the Preview and Email to customer buttons", place: .jobTab("estimate")),
        HelpSpot(id: "jobEstimate.scope", label: "the Scope of work card", place: .jobTab("estimate")),
        HelpSpot(id: "jobSchedule.days", label: "the Crew days card and Add days", place: .jobTab("schedule")),
        HelpSpot(id: "jobSchedule.ticket", label: "the 811 locate ticket card", place: .jobTab("schedule")),
        HelpSpot(id: "jobLogs.add", label: "the Add today's log button", place: .jobTab("logs")),
        HelpSpot(id: "jobPhotos.add", label: "the Add photos button", place: .jobTab("photos")),
        HelpSpot(id: "jobInvoice.card", label: "the invoice card", place: .jobTab("invoice")),
        HelpSpot(id: "schedule.week", label: "the week arrows and Today button", place: .screen("schedule")),
        HelpSpot(id: "schedule.calendar", label: "the Add to Calendar button", place: .screen("schedule")),
        HelpSpot(id: "schedule.unscheduled", label: "the Won, not scheduled card", place: .screen("schedule")),
        HelpSpot(id: "customers.new", label: "the New customer button", place: .screen("customers")),
        HelpSpot(id: "customers.zohoImport", label: "the Import from Zoho button", place: .screen("customers")),
        HelpSpot(id: "settings.zohoImport", label: "the Import from Zoho button in Data & backups", place: .settings("data")),
        HelpSpot(id: "settings.sections", label: "the list of Settings sections", place: .settings("rates")),
        HelpSpot(id: "assistant.mode", label: "the Chat / Action switch", place: .assistant),
        HelpSpot(id: "assistant.composer", label: "the message box", place: .assistant),
        HelpSpot(id: "assistant.attach", label: "the paperclip (attach) button", place: .assistant),
        HelpSpot(id: "assistant.web", label: "the globe (web search) button", place: .assistant),
        HelpSpot(id: "assistant.mic", label: "the microphone (dictation) button", place: .assistant),
        HelpSpot(id: "assistant.history", label: "the clock (earlier chats) button", place: .assistant),
    ]

    static func spot(_ id: String) -> HelpSpot? { spots.first { $0.id == id } }

    // MARK: Articles

    static let articles: [HelpArticle] = [
        // Getting around
        HelpArticle(id: "find-your-way", title: "Find your way around Stringline", area: "Getting around",
                    keywords: ["where", "sidebar", "navigate", "menu", "screens", "find", "go", "open", "around", "lost"],
                    summary: "Everything is in the dark sidebar on the left. Click a name to open that screen.",
                    steps: ["Look at the dark sidebar on the left side of the window.",
                            "Click **Today**, **Pipeline**, **Measure**, **Jobs**, **Schedule**, **Customers** or **Invoices** to open that screen. You can also press ⌘1 through ⌘7.",
                            "Your last few jobs are listed under **Recent jobs**. Click one to open it.",
                            "**Learn Stringline** and **Settings & rates** are at the bottom of the sidebar."],
                    tips: ["Press ⌘K to search for any job or customer by name, address or job number."],
                    screen: "today", spots: ["sidebar.today", "sidebar.recent", "sidebar.settings"]),
        HelpArticle(id: "search", title: "Search for a job or customer", area: "Getting around",
                    keywords: ["search", "find", "look up", "lookup", "command k", "jump", "where is job"],
                    summary: "Search finds jobs and customers by name, address, job number or contact.",
                    steps: ["Press **⌘K**, or click the **Search** box at the top of the sidebar.",
                            "Type part of a name, address or job number.",
                            "Click the job or customer you want. Pressing Return opens the first job."],
                    spots: ["sidebar.search"]),
        HelpArticle(id: "today-screen", title: "What the Today screen shows", area: "Getting around",
                    keywords: ["today", "home", "dashboard", "morning", "weather", "attention", "season", "unpaid", "start"],
                    summary: "Today is the morning check-in: weather, who's working where, and anything that needs you.",
                    steps: ["Click **Today** in the sidebar (⌘1).",
                            "**Paving weather** shows go / no-go for the next days, judged by your weather rules.",
                            "**On the schedule** shows which crew is at which job today.",
                            "**Needs attention** lists rain on job days, 811 tickets running out, quiet bids and late invoices. Each has a button to deal with it.",
                            "Lower down: **Season so far**, **Unpaid by age** and **Due for sealcoat**."],
                    screen: "today", spots: ["today.weather", "today.attention"]),
        HelpArticle(id: "learn", title: "Lessons, the tour and Practice Plaza", area: "Getting around",
                    keywords: ["learn", "lesson", "tour", "tutorial", "practice", "sample", "training", "help", "teach"],
                    summary: "Short lessons and a 2-minute tour, plus a practice job with fake numbers.",
                    steps: ["Click **Learn Stringline** at the bottom of the sidebar.",
                            "Click **Restart the tour** for a six-stop walkthrough.",
                            "Click a lesson card to see its steps, then click its button to try it.",
                            "Click **Open practice job** to try anything on Practice Plaza. **Reset** puts it back the way it was."],
                    screen: "learn", spots: ["sidebar.learn"]),

        // Assistant
        HelpArticle(id: "assistant-basics", title: "Use the AI assistant", area: "Assistant",
                    keywords: ["assistant", "ai", "chatgpt", "chat", "ask", "question", "help", "panel", "command j"],
                    summary: "The assistant answers questions about anything in Stringline and knows which screen you're on.",
                    steps: ["Press **⌘J**, or click **Assistant** in the sidebar, to open the panel on the right.",
                            "Type a question in the message box and press Return. Option-Return starts a new line.",
                            "The bar under the header shows what it can see, like **Sees Maple Ridge Plaza › Estimate**. Click **Hide screen** to stop sending it.",
                            "Click the **Chat / Action** switch to choose whether it only answers (Chat) or can line up changes (Action)."],
                    tips: ["Ask things like “Is this bid in my usual range?” or “How do I add an option?”"],
                    spots: ["sidebar.assistant", "assistant.mode", "assistant.composer"]),
        HelpArticle(id: "assistant-action", title: "Have the assistant make changes", area: "Assistant",
                    keywords: ["action", "change", "apply", "undo", "card", "agent", "do it", "make changes", "automate", "approve"],
                    summary: "In Action mode the assistant lines up changes on a card. Nothing is saved until you press Apply.",
                    steps: ["Click **Action** in the switch at the top of the assistant panel (or press ⌘⇧J).",
                            "Tell it what to do, like “Add crack sealing for 1,200 LF and make it 18% profit.”",
                            "Read the card it makes. Untick anything you don't want.",
                            "Click **Apply**. Changed lines light up on screen.",
                            "Changed your mind? Click **Undo** on the card, or press ⌘Z."],
                    tips: ["Mail drafts, text messages, calendar exports, marking invoices paid and changing rates stay unticked until you tick them.",
                           "You can type while it works to steer it, or click **Stop** (Esc)."],
                    spots: ["assistant.mode"]),
        HelpArticle(id: "address-suggestions", title: "Address suggestions as you type", area: "Getting around",
                    keywords: ["address", "autocomplete", "auto complete", "suggestions", "suggest", "typing address", "apple maps", "lookup", "fill in address", "autofill"],
                    summary: "Address fields suggest real addresses from Apple Maps as you type. Picking one fills in the whole address and, for a job, puts it on the map.",
                    steps: ["Click an address field: a job's **Address**, **New Lead**, a customer's **Billing address**, your **Home base**, or the search on **Measure**.",
                            "Type the first few letters of the address or business. Suggestions appear under the field.",
                            "Press ↓ to move through them and Return to pick one, or click it.",
                            "Stringline fills in the full address. On a job, it also sets where the job is, so **Measure** opens right on the lot."],
                    tips: ["Suggestions lean toward your home base. They come from Apple Maps; no account or key is needed.",
                           "No internet, or a brand-new street Apple doesn't know yet? Just type the address yourself.",
                           "Suggestions need macOS 15 or later."]),
        HelpArticle(id: "import-zoho", title: "Import customers and deals from Zoho (CRM, Bigin or Books)", area: "Customers",
                    keywords: ["zoho", "import", "crm", "bigin", "zoho books", "zoho invoice", "move", "bring in", "transfer", "migrate",
                               "switch", "csv", "export", "accounts", "contacts", "deals", "leads", "copy over"],
                    summary: "Export your customers and deals from Zoho as CSV files, then choose File › Import from Zoho. You see exactly what will be added before anything changes.",
                    steps: ["In Zoho CRM, go to **Setup › Data Administration › Export**. Export **Accounts**, **Contacts** and **Deals** (and **Leads** and **Notes** if you use them), one at a time, as CSV with all fields, so the **Record Id** columns come along.",
                            "Using Bigin, export **Companies**, **Contacts** and **Deals** instead. Using Zoho Books or Zoho Invoice, export your **Customers** as CSV.",
                            "In Stringline, choose **File › Import from Zoho…**, or click **Import from Zoho…** at the top of the Customers screen.",
                            "Select all the files at once and click **Choose**. A .zip that Zoho downloaded works too.",
                            "Check the preview: new customers, new jobs by stage, customers you already have, and anything skipped. Then click **Import**.",
                            "Changed your mind? Click **Undo import**, or press ⌘Z."],
                    tips: ["Companies become customers, and their contacts become the contact person. Deals become jobs at the matching stage: Closed Won is Won, Closed Lost is Lost, Proposal or Negotiation is Sent.",
                           "Customers you already have are matched by email, phone or name. Only their blank fields are filled in; nothing is overwritten. Importing the same files again won't make duplicates.",
                           "Zoho deals usually have no site address, so add one to each job before you measure it.",
                           "Spreadsheet files (.xlsx) won't open here. In Zoho, choose CSV when you export."],
                    screen: "customers", spots: ["customers.zohoImport", "settings.zohoImport"]),
        HelpArticle(id: "assistant-draw", title: "Have the assistant draw on the map", area: "Assistant",
                    keywords: ["draw", "trace", "outline", "parking lot", "measure for me", "fix my drawing", "redraw", "satellite", "auto", "shape", "area"],
                    summary: "In Action mode the assistant can look at a job's satellite view and draw areas, lines and markers for you to check.",
                    steps: ["Open the job's **Measure** tab, then open the assistant (⌘J) and switch to **Action**.",
                            "Ask, for example, “Draw around the parking lot for mill and overlay” or “Fix my outline on the north side.”",
                            "It looks at the lot from above and draws. Its drawing shows as a **dashed white outline** on the map.",
                            "Check it against the picture, then click **Apply** on the card. Not right? Click **Discard**, or tell it what to change.",
                            "After applying, click the area and drag any corner to fine-tune it. ⌘Z undoes the whole drawing."],
                    tips: ["Drawings from the satellite picture are close, not survey-exact. Always look them over before you bid from them.",
                           "Seeing the map needs a ChatGPT account that accepts pictures from apps, or an OpenAI API key."],
                    screen: "job:measure", spots: ["jobMeasure.tools", "assistant.mode"]),
        HelpArticle(id: "assistant-connect", title: "Connect ChatGPT or an OpenAI API key", area: "Assistant",
                    keywords: ["connect", "sign in", "login", "chatgpt", "account", "api key", "disconnect", "plan", "usage", "openai"],
                    summary: "Sign in with your ChatGPT account, or use your own OpenAI API key.",
                    steps: ["Click **Settings & rates** in the sidebar, then **AI assistant**.",
                            "Click **Continue with ChatGPT**. Your browser opens openai.com.",
                            "Sign in there and allow Stringline. Come back to Stringline; it connects by itself.",
                            "To use an API key instead, click **Add API key…**, paste it and click **Save**.",
                            "To sign out, click **Disconnect**. **Manage usage** opens your ChatGPT usage settings."],
                    screen: "settings:assistant", spots: ["settings.sections"]),
        HelpArticle(id: "assistant-attach", title: "Attach photos or PDFs to a question", area: "Assistant",
                    keywords: ["attach", "photo", "picture", "image", "pdf", "file", "upload", "drag", "plans", "screenshot"],
                    summary: "Give the assistant a photo of a lot or a PDF of plans to look at.",
                    steps: ["Open the assistant (⌘J).",
                            "Click the **paperclip** button next to the message box and choose **Choose files…** or **This job's photos…**.",
                            "Or drag pictures or PDFs from Finder or Photos onto the assistant panel.",
                            "Type your question and press Return."],
                    tips: ["Photos are shrunk before sending. PDFs up to 10 MB work."],
                    spots: ["assistant.attach"]),
        HelpArticle(id: "assistant-web", title: "Let the assistant search the web", area: "Assistant",
                    keywords: ["web", "internet", "search online", "google", "price", "news", "sources", "globe", "look up online"],
                    summary: "Turn on web search so the assistant can look things up online, with sources.",
                    steps: ["Open the assistant (⌘J).",
                            "Click the **globe** button by the message box so it's highlighted.",
                            "Ask your question. Answers from the web list their **Sources** underneath; click one to open it."],
                    spots: ["assistant.web"]),
        HelpArticle(id: "assistant-history", title: "Find an earlier conversation", area: "Assistant",
                    keywords: ["history", "earlier", "previous", "old chat", "conversation", "saved", "new chat", "clear"],
                    summary: "Earlier chats are kept on this Mac so you can pick up where you left off.",
                    steps: ["Open the assistant (⌘J).",
                            "Click the **clock** button at the top of the panel.",
                            "Click a conversation to open it, or the trash button to delete it.",
                            "Click **New Chat** in the ⋯ menu to start fresh. Turn history off in Settings › AI assistant."],
                    spots: ["assistant.history"]),
        HelpArticle(id: "assistant-voice", title: "Talk to the assistant and hear answers", area: "Assistant",
                    keywords: ["voice", "talk", "speak", "dictate", "dictation", "microphone", "read aloud", "listen", "hands free"],
                    summary: "Dictate questions with your voice and have answers read out loud.",
                    steps: ["Click the **microphone** button by the message box and start talking. Click it again, or press Return, when you're done.",
                            "To hear an answer, move the pointer over it and click **Read aloud**."],
                    tips: ["Dictation uses macOS Dictation. Turn it on in System Settings › Keyboard if it asks."],
                    spots: ["assistant.mic"]),
        HelpArticle(id: "assistant-privacy", title: "What the assistant sees and sends", area: "Assistant",
                    keywords: ["privacy", "private", "data", "send", "openai", "safe", "secure", "phone numbers", "emails", "hide"],
                    summary: "Each message sends your question and the screen you're on to OpenAI. You control the rest.",
                    steps: ["With each message, Stringline sends your message, the screen you're on and its records, and job and customer names.",
                            "Customer phone numbers and emails are left out unless you turn them on in **Settings › AI assistant**.",
                            "Click **Hide screen** in the assistant panel to stop sending the screen.",
                            "Conversations are kept only on this Mac. Turn that off or clear them in **Settings › AI assistant**."],
                    screen: "settings:assistant"),

        // Leads, jobs, customers
        HelpArticle(id: "new-lead", title: "Add a new lead", area: "Leads and jobs",
                    keywords: ["new lead", "add job", "new job", "create job", "lead", "call", "customer called", "start a job"],
                    summary: "A lead is a new job. Add one the moment someone calls.",
                    steps: ["Press **⌘N**, or click **New lead** on Today, Pipeline or Jobs.",
                            "Type the **Job name**, usually the property, like Maple Ridge Plaza.",
                            "Pick or add the **Customer**, then start typing the **Address** and pick it from the Apple Maps suggestions (↓ then Return, or click it). That also puts the job on the map. You can still type it all and click **Look up**.",
                            "Choose **What they want** and **How they found you**, add any **Notes**.",
                            "Click **Add lead**. It shows up in the Lead column of the Pipeline."],
                    screen: "pipeline", spots: ["pipeline.newLead"]),
        HelpArticle(id: "pipeline-move", title: "Move a job through the pipeline", area: "Leads and jobs",
                    keywords: ["pipeline", "stage", "move", "drag", "sent", "won", "estimating", "site visit", "status", "board"],
                    summary: "The Pipeline board has a column for each stage: Lead, Site visit, Estimating, Sent and Won.",
                    steps: ["Click **Pipeline** in the sidebar (⌘2).",
                            "Drag a job's card to the next column.",
                            "Or right-click the card and choose **Move to** a stage.",
                            "On a job, you can also use the **⋯** button › **Stage**."],
                    tips: ["A bid that's been Sent for a week gets a **Follow up** tag and shows on Today."],
                    screen: "pipeline", spots: ["pipeline.board"]),
        HelpArticle(id: "lost-bid", title: "Mark a bid as lost", area: "Leads and jobs",
                    keywords: ["lost", "didn't win", "declined", "went with someone else", "lose", "show lost"],
                    summary: "Mark lost bids so your win rate stays honest.",
                    steps: ["Open the job.",
                            "Click the **⋯** button at the top right, then **Stage › Lost**.",
                            "On the **Overview** tab, fill in **Why we lost it**.",
                            "To see lost jobs on the Pipeline, click **Show lost**."],
                    screen: "pipeline", spots: ["job.menu", "pipeline.showLost"]),
        HelpArticle(id: "job-details", title: "Change a job's details", area: "Leads and jobs",
                    keywords: ["edit job", "job details", "address", "rename", "bid due", "site visit", "notes", "services", "overview", "customer on job"],
                    summary: "A job's Overview tab holds its name, customer, address, dates, services and notes.",
                    steps: ["Open the job (click it in **Jobs**, **Pipeline** or **Recent jobs**).",
                            "Click the **Overview** tab.",
                            "Change any field. To move the map pin, start typing the **Address** and pick a suggestion, or edit it and click **Find on map**.",
                            "Set **Site visit**, **Pre-bid meeting** and **Bid due** dates. Everything saves by itself."],
                    screen: "job:overview", spots: ["job.tabs"]),
        HelpArticle(id: "delete-job", title: "Delete a job (and get it back)", area: "Leads and jobs",
                    keywords: ["delete", "remove", "trash", "get rid of", "restore job", "undelete", "deleted by mistake"],
                    summary: "Deleted jobs go to the Trash, and History can bring them back.",
                    steps: ["Open the job.",
                            "Click the **⋯** button at the top right, then **Move to Trash…**, and confirm.",
                            "To bring it back, choose **File › Browse History…** (⇧⌘Y), find the job and click **Restore Job…**."],
                    spots: ["job.menu"]),
        HelpArticle(id: "customers", title: "Add or change a customer", area: "Leads and jobs",
                    keywords: ["customer", "contact", "phone", "email", "client", "add customer", "edit customer", "delete customer"],
                    summary: "The Customers screen keeps contact info and every job you've done for each customer.",
                    steps: ["Click **Customers** in the sidebar (⌘6).",
                            "Click **New customer**, or pick one from the list.",
                            "Fill in **Name**, **Contact person**, **Phone**, **Email**, **Billing address** (suggestions from Apple Maps appear as you type) and **Notes**.",
                            "Click **New job** to start a job for them. **Delete…** removes the customer but keeps their jobs."],
                    screen: "customers", spots: ["customers.new"]),

        // Measure
        HelpArticle(id: "measure-lot", title: "Measure a parking lot from satellite", area: "Measure",
                    keywords: ["measure", "area", "square feet", "square yards", "sy", "satellite", "outline", "draw", "map", "takeoff", "how big", "size"],
                    summary: "Outline the pavement on a satellite photo and Stringline works out square feet, square yards and tons.",
                    steps: ["Click **Measure** in the sidebar (⌘3) and start typing the address or business in **Where's the lot?**. Pick a suggestion, then the result. (On an existing job, click its **Measure** tab.)",
                            "Zoom in until you can see the stall lines.",
                            "Press **A** for the Area tool, then click each corner of the pavement.",
                            "Press **Return** to close the shape.",
                            "On the right, rename it (like Main lot) and set the **Depth**."],
                    tips: ["Satellite numbers are good for bidding. On big jobs, check them on site with a wheel."],
                    screen: "job:measure", spots: ["measure.search", "jobMeasure.tools"]),
        HelpArticle(id: "measure-cutout", title: "Cut out islands and buildings", area: "Measure",
                    keywords: ["cut out", "island", "building", "subtract", "remove area", "landscaping", "hole", "exclude"],
                    summary: "Cut-outs subtract islands and buildings so you only bid what gets paved.",
                    steps: ["Open the job's **Measure** tab.",
                            "Press **X** for the Cut out tool.",
                            "Click around the island or building inside an area.",
                            "Press **Return**. The area's square footage drops by that amount.",
                            "To undo it, select the area and click **Remove** under its cut-outs."],
                    screen: "job:measure", spots: ["jobMeasure.tools"]),
        HelpArticle(id: "measure-lines-counts", title: "Measure lines and count stalls", area: "Measure",
                    keywords: ["line", "linear feet", "lf", "striping", "crack", "curb", "count", "stalls", "ada", "arrows", "markers"],
                    summary: "Lines measure lengths (striping, cracks, curb). Count markers count stalls, ADA spots and arrows.",
                    steps: ["Open the job's **Measure** tab.",
                            "For a length, press **L**, click along the line, then press **Return** to finish it.",
                            "For counts, press **C** and click once per stall, ADA spot or arrow.",
                            "Counting a whole row? Drop one marker and set **Stands for** to how many it represents.",
                            "Pick the work type on the right, like Striping or Crack seal."],
                    screen: "job:measure", spots: ["jobMeasure.tools"]),
        HelpArticle(id: "measure-edit", title: "Fix a measured shape", area: "Measure",
                    keywords: ["fix", "edit shape", "move corner", "drag", "delete shape", "rename area", "depth", "undo", "select", "wrong"],
                    summary: "Select a shape to move its corners, rename it, change its depth or delete it.",
                    steps: ["Open the job's **Measure** tab.",
                            "Press **V** for Select, then click the shape.",
                            "Drag a corner to move it.",
                            "On the right, change the **Name**, **Work** type or **Depth**, or click **Delete**.",
                            "Made a mistake? Press **⌘Z** to undo. Press **Esc** to stop drawing."],
                    screen: "job:measure", spots: ["jobMeasure.tools"]),
        HelpArticle(id: "measure-imagery", title: "Switch satellite photos and use Look Around", area: "Measure",
                    keywords: ["imagery", "old photo", "blurry", "esri", "apple maps", "look around", "street view", "outdated", "trees"],
                    summary: "Two satellite sources, taken on different dates, plus street-level Look Around.",
                    steps: ["Open the job's **Measure** tab.",
                            "If the photo looks old, click **Esri** (or **Apple**) in the switch at the top of the map.",
                            "Click **Look Around** to see the lot from the street, from Apple Maps."],
                    screen: "job:measure", spots: ["jobMeasure.imagery", "jobMeasure.lookAround"]),

        // Estimates and proposals
        HelpArticle(id: "estimate-build", title: "Build an estimate", area: "Estimates",
                    keywords: ["estimate", "bid", "price", "quote", "build estimate", "send to estimate", "how much", "pricing"],
                    summary: "Your measurements become priced line items using your rates.",
                    steps: ["Open the job's **Measure** tab and click **Send to estimate**.",
                            "Or open the **Estimate** tab and click **Build from measurements** (or **Start blank**).",
                            "Check each line. Change any quantity or unit cost right in the table.",
                            "Set your markup in the **Bid summary** on the right."],
                    screen: "job:estimate", spots: ["jobMeasure.send", "jobEstimate.lines"]),
        HelpArticle(id: "estimate-lines", title: "Add, change or remove line items", area: "Estimates",
                    keywords: ["line item", "add line", "remove line", "change price", "unit cost", "quantity", "edit estimate", "update from measurements"],
                    summary: "Every line is editable. Prices come from your rates, and changing one here only affects this job.",
                    steps: ["Open the job's **Estimate** tab.",
                            "To add a line, click **Add line item** under the table and pick a price from your rates, or a blank line.",
                            "To change a line, click its quantity or unit cost and type.",
                            "To remove a line, click the round minus button at the end of its row.",
                            "After re-measuring, click **Update from measurements**. Your own lines and changed prices stay."],
                    screen: "job:estimate", spots: ["jobEstimate.lines"]),
        HelpArticle(id: "estimate-markup", title: "Set profit and overhead", area: "Estimates",
                    keywords: ["profit", "margin", "markup", "overhead", "slider", "price per sy", "per square yard", "usual range", "too high", "too low"],
                    summary: "The Bid summary turns cost into a bid price with your overhead and profit.",
                    steps: ["Open the job's **Estimate** tab.",
                            "In the dark **Bid summary** on the right, type the **Overhead** percent.",
                            "Drag the **Profit** slider. The bid price, price per SY and margin change as you drag.",
                            "The bar underneath compares your price per SY with your recent won jobs."],
                    screen: "job:estimate", spots: ["jobEstimate.summary"]),
        HelpArticle(id: "estimate-options", title: "Offer the customer options (A, B, C)", area: "Estimates",
                    keywords: ["option", "options", "alternate", "choice", "option b", "sealcoat only", "duplicate", "copy option", "delete option"],
                    summary: "Options let the customer choose, like mill & overlay or sealcoat only.",
                    steps: ["Open the job's **Estimate** tab.",
                            "Click **Add option** and choose **Copy of this option**, **Build from measurements** or **Blank option**.",
                            "Click an option's button at the top to switch to it.",
                            "Right-click an option for **Duplicate** or **Delete option**."],
                    tips: ["The option that's selected goes first on the proposal."],
                    screen: "job:estimate", spots: ["jobEstimate.options"]),
        HelpArticle(id: "estimate-scope", title: "Write the scope of work", area: "Estimates",
                    keywords: ["scope", "scope of work", "description", "what we'll do", "exclusions", "terms", "wording"],
                    summary: "The scope of work is what the customer reads on the proposal.",
                    steps: ["Open the job's **Estimate** tab and scroll to **Scope of work**.",
                            "Type one step per line.",
                            "Click **Rewrite from measurements** to start over from your takeoff.",
                            "Exclusions and payment terms come from Settings; click **Edit** to change them."],
                    screen: "job:estimate", spots: ["jobEstimate.scope"]),
        HelpArticle(id: "proposal-send", title: "Preview and email a proposal", area: "Estimates",
                    keywords: ["proposal", "send", "email", "pdf", "preview", "mail", "send bid", "customer copy"],
                    summary: "Stringline makes a two-page PDF with your logo and a satellite picture, and opens it in Mail.",
                    steps: ["Open the job's **Estimate** tab.",
                            "Click **Preview** to see the PDF.",
                            "Click **Email to customer**. Mail opens a draft with the PDF attached.",
                            "Check it and press Send in Mail. The job moves to Sent."],
                    tips: ["A copy of the PDF is saved in the job's docs folder."],
                    screen: "job:estimate", spots: ["jobEstimate.send"]),
        HelpArticle(id: "follow-up", title: "Follow up on a quiet bid", area: "Estimates",
                    keywords: ["follow up", "follow-up", "no answer", "quiet", "remind customer", "check in", "chase"],
                    summary: "Bids sent a week ago with no answer show up on Today with a Follow up button.",
                    steps: ["Click **Today** in the sidebar.",
                            "Find **Follow up: (job name)** under **Needs attention**.",
                            "Click **Follow up**. Mail opens a short, friendly check-in to the customer.",
                            "Press Send in Mail."],
                    screen: "today", spots: ["today.attention"]),

        // Schedule and running jobs
        HelpArticle(id: "schedule-job", title: "Put a won job on the schedule", area: "Schedule",
                    keywords: ["schedule", "book", "crew", "date", "calendar", "plan", "assign crew", "when", "won job"],
                    summary: "Book crew days for a won job. Each day is checked against your weather rules.",
                    steps: ["Click **Schedule** in the sidebar (⌘5).",
                            "Under **Won, not scheduled**, click **Schedule** next to the job.",
                            "Pick the **Crew**, the **First day**, how many days, and the **Start time**.",
                            "Check the weather for those days, then click **Schedule**."],
                    tips: ["You can also open the job's **Schedule** tab and click **Add days**. Only won jobs go on the schedule."],
                    screen: "schedule", spots: ["schedule.unscheduled", "jobSchedule.days"]),
        HelpArticle(id: "schedule-change", title: "Move or remove a crew day", area: "Schedule",
                    keywords: ["move day", "reschedule", "change day", "change crew", "remove day", "rain delay", "push back", "next week"],
                    summary: "Click a day on the schedule to change it.",
                    steps: ["Click **Schedule** in the sidebar.",
                            "Use the arrows (or **Today**) at the top to find the week.",
                            "Click the job's card on that day.",
                            "Change the **Day**, **Crew**, **Start time** or **Note**, or click **Remove day**."],
                    screen: "schedule", spots: ["schedule.week"]),
        HelpArticle(id: "weather-rules", title: "How the go / no-go weather check works", area: "Schedule",
                    keywords: ["weather", "rain", "cold", "temperature", "go no go", "forecast", "red card", "no-go", "rules", "sealcoat weather"],
                    summary: "Every job day is checked against your rules. A red card means move it.",
                    steps: ["Paving needs your minimum temperature and rising. Sealcoat, crack seal and striping need it to stay warm day and night.",
                            "Any day at or over your rain chance is a no-go.",
                            "To change the rules, click **Settings & rates**, then **Weather rules**.",
                            "The forecast is for your home base. Set it in **Settings › Company**."],
                    screen: "settings:weather", spots: ["today.weather"]),
        HelpArticle(id: "ticket-811", title: "Track the 811 locate ticket", area: "Schedule",
                    keywords: ["811", "locate", "ticket", "utilities", "dig", "miss dig", "call before you dig"],
                    summary: "Keep the ticket number and expiry on the job, and Stringline warns you before it runs out.",
                    steps: ["Open the job and click the **Schedule** tab.",
                            "In **811 locate ticket**, type the **Ticket number** and the **Good until** date.",
                            "If it's surface work only, tick **Not needed for this job**.",
                            "Today warns you two days before the ticket runs out."],
                    screen: "job:schedule", spots: ["jobSchedule.ticket"]),
        HelpArticle(id: "plant-order", title: "Record the plant order", area: "Schedule",
                    keywords: ["plant", "order", "asphalt order", "tons", "mix order", "supplier"],
                    summary: "Note what you ordered from the plant so it shows on Today and the schedule.",
                    steps: ["Open the job and click the **Schedule** tab.",
                            "In **Plant order**, type what you ordered, like “310 tn surface, confirmed with the plant”."],
                    screen: "job:schedule"),
        HelpArticle(id: "calendar", title: "Send the schedule to Apple Calendar", area: "Schedule",
                    keywords: ["calendar", "apple calendar", "ical", "export", "phone calendar", "add to calendar", "sync"],
                    summary: "Add a week of crew days to Apple Calendar so they're on your iPhone too.",
                    steps: ["Click **Schedule** in the sidebar and go to the week.",
                            "Click **Add to Calendar**.",
                            "Calendar opens and asks which calendar to add them to."],
                    screen: "schedule", spots: ["schedule.calendar"]),
        HelpArticle(id: "directions", title: "Get directions to a job in Apple Maps", area: "Schedule",
                    keywords: ["directions", "drive", "maps", "apple maps", "navigate", "how far", "drive time", "route", "address"],
                    summary: "Open any job in Apple Maps for directions.",
                    steps: ["Open the job.",
                            "Click the **⋯** button at the top right.",
                            "Choose **Open in Maps** to see it, or **Directions** to drive there."],
                    tips: ["Ask the assistant “How long is the drive to Maple Ridge?” for drive time from your home base."],
                    spots: ["job.menu"]),
        HelpArticle(id: "daily-logs", title: "Log tons and hours each day", area: "Running jobs",
                    keywords: ["log", "daily log", "tons", "hours", "actuals", "job cost", "how close", "bid vs actual"],
                    summary: "Daily logs show how close your bid was.",
                    steps: ["Open the job and click the **Daily logs** tab.",
                            "Click **Add today's log**.",
                            "Fill in **Tons laid**, **Crew hours**, **Weather** and **Notes**.",
                            "The bars under **How close was the bid?** compare your actuals with the estimate."],
                    screen: "job:logs", spots: ["jobLogs.add"]),
        HelpArticle(id: "photos", title: "Add job photos", area: "Running jobs",
                    keywords: ["photo", "photos", "pictures", "before and after", "airdrop", "images", "camera"],
                    summary: "Keep before and after shots, plant tickets and problems with the job.",
                    steps: ["Open the job and click the **Photos** tab.",
                            "Click **Add photos**, or drag them in from Photos, Finder or AirDrop.",
                            "Click **Show folder** to see them in Finder."],
                    screen: "job:photos", spots: ["jobPhotos.add"]),

        // Money
        HelpArticle(id: "invoice-create", title: "Create and send an invoice", area: "Money",
                    keywords: ["invoice", "bill", "billing", "charge", "send invoice", "create invoice", "get paid", "deposit", "terms"],
                    summary: "Turn a won job into an invoice and email it as a PDF.",
                    steps: ["Open the won job and click the **Invoice** tab.",
                            "Click **Create invoice**. The amount starts at the price of the option you picked.",
                            "Set the **Terms** (like Net 30), any **Deposit received** and a **Note on the invoice**.",
                            "Click **Email invoice**. Mail opens with the PDF attached."],
                    screen: "job:invoice", spots: ["jobInvoice.card"]),
        HelpArticle(id: "invoice-paid", title: "Mark an invoice paid", area: "Money",
                    keywords: ["paid", "payment", "check came", "mark paid", "late", "overdue", "unpaid", "aging", "who owes"],
                    summary: "Mark invoices paid when the check comes in. Late ones show up on Today.",
                    steps: ["Click **Invoices** in the sidebar (⌘7), or open the job's **Invoice** tab.",
                            "Find the invoice and click **Mark paid**.",
                            "Clicked it by mistake? Click **Mark unpaid**."],
                    tips: ["**Unpaid by age** on Today shows what's owed and how late."],
                    screen: "invoices", spots: ["sidebar.invoices"]),

        // Settings and data
        HelpArticle(id: "rates", title: "Change your prices and markup", area: "Settings",
                    keywords: ["rates", "prices", "cost", "unit cost", "price list", "default profit", "overhead default", "waste", "mix weight", "truck size", "tack"],
                    summary: "Your price list and quantity factors feed every new estimate.",
                    steps: ["Click **Settings & rates** in the sidebar (⌘,).",
                            "Click **Rates & markup**.",
                            "Change any price, or click **Add a price**.",
                            "Set **Default profit** and **Overhead**, and the **Quantities** like mix weight, waste and truck size."],
                    tips: ["Changes apply to new estimates. Bids you've already sent keep their numbers."],
                    screen: "settings:rates", spots: ["settings.sections"]),
        HelpArticle(id: "company", title: "Set your company info, logo and home base", area: "Settings",
                    keywords: ["company", "logo", "name", "phone", "license", "home base", "address", "letterhead", "branding"],
                    summary: "This goes at the top of every proposal and invoice.",
                    steps: ["Click **Settings & rates**, then **Company**.",
                            "Fill in your company name, phone, email and address.",
                            "Drop your logo on the logo box, or click it to choose a file.",
                            "Under **Home base**, start typing your town and pick it from the suggestions (or click **Find**), or click **Use this Mac's location**."],
                    screen: "settings:company", spots: ["settings.sections"]),
        HelpArticle(id: "crews", title: "Add or change crews", area: "Settings",
                    keywords: ["crew", "crews", "team", "employees", "equipment", "add crew", "workers"],
                    summary: "Each crew gets its own row on the schedule.",
                    steps: ["Click **Crews** in the sidebar (or **Settings & rates › Crews & equipment**).",
                            "Click **Add a crew**.",
                            "Set its name, what it does, how many people and its equipment."],
                    screen: "settings:crews", spots: ["sidebar.crews"]),
        HelpArticle(id: "proposal-wording", title: "Change proposal wording and reminders", area: "Settings",
                    keywords: ["proposal wording", "exclusions", "terms", "valid days", "escalation", "numbering", "reseal reminder", "proposal number"],
                    summary: "The standard wording on every proposal, and when to remind past customers.",
                    steps: ["Click **Settings & rates**, then **Proposals & reminders**.",
                            "Set how long **Proposals good for** lasts, and edit the exclusions and terms.",
                            "Turn the asphalt **Price adjustment clause** on or off.",
                            "Set **Remind about resealing after** for sealcoat reminders, and the next proposal and invoice numbers."],
                    screen: "settings:proposal", spots: ["settings.sections"]),
        HelpArticle(id: "sealcoat-reminders", title: "Remind past customers to reseal", area: "Settings",
                    keywords: ["reseal", "sealcoat reminder", "repeat business", "past customers", "due for sealcoat", "remind"],
                    summary: "Finished sealcoat jobs come back on Today when it's time to reseal.",
                    steps: ["Click **Today** and scroll to **Due for sealcoat**.",
                            "Click **Remind** next to a customer. Mail opens a short note.",
                            "Change how many years that takes in **Settings › Proposals & reminders**."],
                    screen: "today"),
        HelpArticle(id: "data-folder", title: "Where your data lives, and backups", area: "Data",
                    keywords: ["data", "folder", "pavingdata", "files", "backup", "icloud", "finder", "where saved", "time machine", "export"],
                    summary: "Everything is plain files in one PavingData folder. Nothing is in an account or a server.",
                    steps: ["Click the **PavingData folder** card at the bottom of the sidebar to see Data & backups.",
                            "Each job is its own folder with its files, photos and PDFs.",
                            "A backup is made every night; click **Back up now** for one right away.",
                            "If the folder is in iCloud Drive, your iPhone's Files app can open proposals in each job's docs folder."],
                    tips: ["In Finder, right-click PavingData and choose Keep Downloaded so jobs open with no internet."],
                    screen: "settings:data", spots: ["sidebar.data"]),
        HelpArticle(id: "history-restore", title: "Undo a mistake or put back an old version", area: "Data",
                    keywords: ["undo", "history", "restore", "old version", "mistake", "go back", "recover", "accident", "previous version"],
                    summary: "Every save is kept on this Mac, so any file or job can be put back.",
                    steps: ["For something you just did, press **⌘Z**.",
                            "For older changes, choose **File › Browse History…** (⇧⌘Y), or on a job click **⋯ › History…**.",
                            "Pick the job or file on the left, then a version on the right.",
                            "Click **Restore…** and confirm. Deleted jobs have **Restore Job…**."],
                    tips: ["Every save is kept for two weeks, one an hour back to 90 days, then one a day for two years."],
                    spots: ["job.menu"]),
        HelpArticle(id: "two-macs", title: "Use Stringline on two Macs", area: "Data",
                    keywords: ["two macs", "another mac", "laptop", "office", "saving paused", "use this mac", "just look", "two versions", "conflict", "sync"],
                    summary: "Point both Macs at the same PavingData folder in iCloud Drive. One Mac saves at a time.",
                    steps: ["On the second Mac, choose **I already use Stringline on another Mac** during setup, and pick the same PavingData folder.",
                            "If Stringline is open on the other Mac, you'll be asked **Use This Mac** or **Just Look**.",
                            "If a file changed on both Macs, Stringline shows **Two versions** and you pick the one to keep. The other stays in History."],
                    screen: "settings:data"),
        HelpArticle(id: "check-data", title: "Check your files for problems", area: "Data",
                    keywords: ["check", "health", "damaged", "broken", "problem", "error", "repair", "fix files", "corrupt"],
                    summary: "The health check opens every file and offers a one-click fix for anything wrong.",
                    steps: ["Choose **File › Check My Data**, or click **Settings & rates › Data & backups**.",
                            "Click **Check Now**.",
                            "Anything that needs a look is listed with a button to fix it."],
                    screen: "settings:data"),
    ]

    static func article(_ id: String) -> HelpArticle? { articles.first { $0.id == id } }

    // MARK: Search

    private static let synonyms: [String: [String]] = [
        "bid": ["estimate", "proposal"], "quote": ["estimate", "proposal"], "price": ["estimate", "rates", "profit"],
        "pricing": ["estimate", "rates"], "cost": ["rates", "estimate"], "margin": ["profit"], "markup": ["profit", "overhead"],
        "email": ["mail", "proposal", "send"], "mail": ["email", "send"], "send": ["email", "proposal"],
        "map": ["measure", "maps"], "satellite": ["measure"], "draw": ["measure", "outline"], "footage": ["measure", "area"],
        "yards": ["measure", "area"], "tonnage": ["tons"], "delete": ["trash", "remove"], "remove": ["delete"],
        "bill": ["invoice"], "pay": ["paid", "invoice"], "owe": ["unpaid", "invoice"], "late": ["overdue", "invoice"],
        "client": ["customer"], "contact": ["customer"], "book": ["schedule"], "date": ["schedule"], "crew": ["schedule", "crews"],
        "rain": ["weather"], "cold": ["weather"], "forecast": ["weather"], "backup": ["backups", "data"], "lost": ["lost"],
        "chatgpt": ["assistant", "connect"], "ai": ["assistant"], "login": ["connect", "sign in"], "voice": ["dictation"],
        "picture": ["photo"], "image": ["photo", "attach"], "upload": ["attach"], "online": ["web"], "internet": ["web"],
        "directions": ["maps", "drive"], "drive": ["directions", "maps"], "undo": ["history", "undo"], "restore": ["history"],
        "job": ["job"], "lead": ["lead"], "where": ["where", "find"],
    ]

    static func tokens(_ text: String) -> [String] {
        let lowered = text.lowercased().replacingOccurrences(of: "’", with: "'")
        let words = lowered.split { !($0.isLetter || $0.isNumber || $0 == "'") }.map(String.init)
        let stop: Set<String> = ["a", "an", "the", "i", "do", "how", "to", "my", "of", "in", "on", "for", "is", "it", "can", "and", "or", "with",
                                 "what", "this", "that", "me", "you", "your", "be", "are", "does", "at", "from", "up", "get", "want", "need", "i'm", "it's"]
        return words.filter { !stop.contains($0) && $0.count > 1 }.map(stem)
    }

    static func stem(_ word: String) -> String {
        var w = word
        for suffix in ["ing", "ed", "es", "s"] where w.count > suffix.count + 2 && w.hasSuffix(suffix) {
            w.removeLast(suffix.count)
            break
        }
        return w
    }

    /// Best matching articles first.
    static func search(_ query: String, limit: Int = 4) -> [HelpArticle] {
        let base = tokens(query)
        guard !base.isEmpty else { return [] }
        var terms = Set(base)
        for word in base { for s in synonyms[word] ?? [] { terms.formUnion(tokens(s)) } }
        let phrase = query.lowercased()
        let scored: [(HelpArticle, Double)] = articles.map { a in
            let title = Set(tokens(a.title))
            let keys = Set(a.keywords.flatMap(tokens))
            let summary = Set(tokens(a.summary))
            let body = Set(a.steps.flatMap(tokens))
            var score = 0.0
            for t in terms {
                let weight = base.contains(t) ? 1.0 : 0.5
                if title.contains(t) { score += 3 * weight }
                if keys.contains(t) { score += 2.5 * weight }
                if summary.contains(t) { score += 1 * weight }
                if body.contains(t) { score += 0.4 * weight }
            }
            for keyword in a.keywords where keyword.contains(" ") && phrase.contains(keyword) { score += 4 }
            return (a, score)
        }
        return scored.filter { $0.1 >= 2 }.sorted { $0.1 > $1.1 }.prefix(limit).map(\.0)
    }

    /// Articles about the screen with this key (e.g. "job:estimate", "schedule").
    static func articles(forScreen key: String) -> [HelpArticle] {
        articles.filter { $0.screen == key }
    }

    static func json(_ a: HelpArticle, full: Bool) -> JSONValue {
        var o: [String: JSONValue] = ["id": .string(a.id), "title": .string(a.title), "area": .string(a.area), "summary": .string(a.summary)]
        if full {
            o["steps"] = .array(a.steps.map { .string($0) })
            o["tips"] = .array(a.tips.map { .string($0) })
            o["take_me_there"] = .from(a.screen)
            o["show_me_spots"] = .array(a.spots.compactMap { id in spot(id).map { ["id": .string($0.id), "what": .string($0.label)] } })
        }
        return .object(o)
    }
}
